version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - "8989:8989"
    environment:
      - DATA_SOURCE_URL=${DATA_SOURCE_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - DATA_SOURCE_USERNAME=${DATA_SOURCE_USERNAME}
      - DATA_SOURCE_PASSWORD=${DATA_SOURCE_PASSWORD}
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0.34"
    container_name: "mysqldb"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_SOURCE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

